export const CANVAS_BACKGROUND = "#3b3b3b";
export const EPSILON = 1e-6;
export const FAR_CLIPPING_PLANE = 12.0;
export const FOV = Math.PI * (60 / 180);
export const LINE_WIDTH = 0.05;
export const NEAR_CLIPPING_PLANE = 1.25;
export const PLAYER_STEP_LENGTH = 0.5;
export const POINT_RADIUS = 0.12;
export const SCREEN_WIDTH = 100;
